Repository Biancars/devops-aula-07, pull requests merged in 2018-09, with the labels that each got.

#4 Integrar arquitetura v1.0
  README.md
  docs/arquitetura.md
  docs/requisitos.md
Labels: arquitetura

#6 Integrar implementação v1.0
  src/jogovelha.py
Labels: programação

#8 Integrar testes v1.0
  src/testes_inic.py
  src/testes_jogar.py
Labels: testes

#9 Gerar release v1.0
  src/jogovelha.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: operações

#11 INTEGRAR REQUISITOS V1.1
  docs/requisito2.md
Labels: análise

#15 validacao
  src/validacao_jogo.py
Labels: programação

#17 V1.1 testes
  src/Teste_validacao.py
  src/teste_novas_validacoes.py
Labels: testes

#18 Gerar release v1.1
  docs/arquitetura_jogos.md
  docs/requisito2.md
  src/Teste_validacao.py
  src/teste_novas_validacoes.py
  src/validacao_jogo.py
Labels: operações
